{
 "title": "Backend Log",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "level",
    "label": "Level",
    "query": "INFO, WARNING, ERROR, DEBUG, CRITICAL"
   },
   { "name": "message", "label": "Message" }
  ]
 },
 "panels": [
  {
   "title": "Module Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"backend_logs\"} |= \"\""
    }
   ]
  },
  {
   "title": "API Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"backend_logs\"}"
    }
   ]
  },
  {
   "title": "API Method Distribution",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"backend_logs\"}"
    }
   ]
  },
  {
   "title": "Level Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "(\r\n  count by(level) (rate({job=\"backend_logs\"} [$__auto]))\r\n) or (\r\n  label_replace(vector(0), \"level\", \"DEBUG\", \"\", \"\")\r\n) or (\r\n  label_replace(vector(0), \"level\", \"INFO\", \"\", \"\")\r\n) or (\r\n  label_replace(vector(0), \"level\", \"WARNING\", \"\", \"\")\r\n) or (\r\n  label_replace(vector(0), \"level\", \"ERROR\", \"\", \"\")\r\n) or (\r\n  label_replace(vector(0), \"level\", \"CRITICAL\", \"\", \"\")\r\n)",
     "maxLines": 50000
    }
   ]
  },
  {
   "title": "Level Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "(\r\n  count by(level) (rate({job=\"backend_logs\"} [$__auto]))\r\n) or (\r\n  label_replace(vector(0), \"level\", \"DEBUG\", \"\", \"\")\r\n) or (\r\n  label_replace(vector(0), \"level\", \"INFO\", \"\", \"\")\r\n) or (\r\n  label_replace(vector(0), \"level\", \"WARNING\", \"\", \"\")\r\n) or (\r\n  label_replace(vector(0), \"level\", \"ERROR\", \"\", \"\")\r\n) or (\r\n  label_replace(vector(0), \"level\", \"CRITICAL\", \"\", \"\")\r\n)",
     "maxLines": 50000
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "(\r\n  count by(level) (rate({job=\"backend_logs\"} |= \"DEBUG\" [$__auto]))\r\n) or (\r\n  label_replace(vector(0), \"level\", \"DEBUG\", \"\", \"\")\r\n)",
     "maxLines": 50000
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "(\r\n  count by(level) (rate({job=\"backend_logs\"} |= \"INFO\" [$__auto]))\r\n) or (\r\n  label_replace(vector(0), \"level\", \"INFO\", \"\", \"\")\r\n)",
     "maxLines": 50000
    }
   ]
  },
  {
   "title": "Log List",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"backend_logs\"} \r\n  | level =~ \"${level:pipe:.*}\" \r\n  |= \"${message:pipe:.*}\"\r\n  | keep timestamp, level, logger, message, method, path, status_code, user_agent, ip_address",
     "maxLines": 5000
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "(\r\n  count by(level) (rate({job=\"backend_logs\"} |= \"WARNING\" [$__auto]))\r\n) or (\r\n  label_replace(vector(0), \"level\", \"WARNING\", \"\", \"\")\r\n)",
     "maxLines": 50000
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "(\r\n  count by(level) (rate({job=\"backend_logs\"} |= \"ERROR\" [$__auto]))\r\n) or (\r\n  label_replace(vector(0), \"level\", \"ERROR\", \"\", \"\")\r\n)",
     "maxLines": 50000
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "(\r\n  count by(level) (rate({job=\"backend_logs\"} |= \"CRITICAL\" [$__auto]))\r\n) or (\r\n  label_replace(vector(0), \"level\", \"CRITICAL\", \"\", \"\")\r\n)",
     "maxLines": 50000
    }
   ]
  }
 ]
}