"""Created webpush subscription model

Revision ID: 3d805d050e06
Revises: 52254da1da1c
Create Date: 2025-07-14 09:34:20.211545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d805d050e06'
down_revision: Union[str, None] = '52254da1da1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webpush_subscription',
    sa.Column('id', sa.String(length=36), nullable=False, comment='訂閱 ID'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='使用者 ID'),
    sa.Column('endpoint', sa.Text(), nullable=False, comment='訂閱的 Endpoint'),
    sa.Column('keys', sa.JSON(), nullable=False, comment='訂閱的 Keys'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否有效'),
    sa.Column('user_agent', sa.String(length=255), nullable=False, comment='使用者代理'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新時間'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webpush_subscription')
    # ### end Alembic commands ###
