"""Created websocket events model

Revision ID: 52254da1da1c
Revises: 
Create Date: 2025-07-14 09:33:46.571710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '52254da1da1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('endpoint'), table_name='webpush_subscription')
    op.drop_table('webpush_subscription')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webpush_subscription',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False, comment='訂閱 ID'),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False, comment='使用者 ID'),
    sa.Column('endpoint', mysql.TEXT(), nullable=False, comment='訂閱的 Endpoint'),
    sa.Column('keys', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False, comment='訂閱的 Keys'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否有效'),
    sa.Column('user_agent', mysql.VARCHAR(length=255), nullable=False, comment='使用者代理'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='建立時間'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True, comment='更新時間'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('endpoint'), 'webpush_subscription', ['endpoint'], unique=True)
    # ### end Alembic commands ###
